output "worker_iam_role_arn" {
  description = "Worker IAM Role"
  value       = module.eks.worker_iam_role_arn
}

output "worker_iam_role_name" {
  description = "Worker IAM Role Name"
  value       = module.eks.worker_iam_role_name
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "kubeconfig_filename" {
  description = "The filename of the generated kubectl config."
  value       = module.eks.kubeconfig_filename
}

output "config_map_aws_auth" {
  description = ""
  value       = module.eks.config_map_aws_auth
}

output "cluster_id" {
  description = "cluster_id"
  value       = module.eks.cluster_id
}

output "worker_security_group_id" {
  description = "The Id of the worker nodes security group"
  value       = module.eks.worker_security_group_id
}
